version: 2.1
jobs:
    build:
        working_directory: ~/courses-viewer-app
        docker:
            - image: circleci/node:10.16.3
        steps:
            - run:
                  name: Install Dependencies
                  command: yarn install
            - run:
                  name: Run tests
                  command: yarn test
orbs:
    heroku: circleci/heroku@0.0.10
workflows:
    heroku_deploy:
        jobs:
            - build
            - heroku/deploy-via-git
