orbs:
  react: thefrontside/react@0.2.0
version: 2.1
jobs:
  install:
    steps:
      - react/install
  tests:
    steps:
      - react/eslint:
          requires:
            - install
      - react/test:
          requires:
            - install
      - react/coverage:
          requires:
            - install
  deploy:
    steps:
      - react/eslint:
          requires:
            - tests
workflows:
  test_and_deploy:
    jobs:
      - install
      - tests:
          requires:
            - install
      - deploy:
          requires:
            - tests




# orbs:
#     heroku: circleci/heroku@0.0.10
#     node: circleci/node@4.1.0
# version: 2.1

# # Define the jobs we want to run for this project
# jobs:
#   test:
#     - node/test
#   deploy:
#     - heroku/deploy-via-git:

# # Orchestrate our job run sequence
# workflows:
#   test-and-deploy:
#     jobs:
#       - node/test
#       - heroku/deploy-via-git:
#           filters:
#             branches:
#               only:
#                 - main
#           requires:
#             - node/test