orbs:
    heroku: circleci/heroku@0.0.10
    node: circleci/node@4.1.0

version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    - node/test
    - run: echo "Running tests"
  deploy:
    - heroku/deploy-via-git:

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - test  
  
