orbs:
  react: thefrontside/react@0.2.0
version: 2.1
jobs:
  install:
    steps:
      - react/install
  deploy:
    machine:
        enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh -p 43002 $SSH_USER@$SSH_HOST "cd /var/www/html/courses-viewer-app; git pull;"

workflows:
  build:
    jobs:
      - install

  test:
    jobs:
      - react/install
      - react/eslint:
          requires:
            -install
      - react/test:
          requires:
            -install
      - react/coverage:
          requires:
            -install

  deploy_dev:
    jobs:      
      - deploy/dev:
          type: approval
          machine:
            enabled: true
          steps:
            - run:
                name: Deploy Over SSH
                command: ssh -p 43002 $SSH_USER@$SSH_HOST "cd /var/www/html/dev/courses-viewer-app; git pull;"
          filters:
            branches:
              ignore:
                - main
          requires:
            -tests
    deploy:
      jobs:
        filters:
          branches:
            only:
              - main
        requires:
          - react/eslint
          - react/test
          - react/coverage
        