orbs:
    heroku: circleci/heroku@0.0.10
    node: circleci/node@4.1.0
version: 2.1
jobs:
  test:
    jobs:
      - node/test
  deploy:
    jobs:
      - heroku/deploy-via-git

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - node/test
  
        
