orbs:
  react: thefrontside/react@0.2.0
version: 2.1
jobs:
  deploy:
    machine:
        enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh -p 43002 $SSH_USER@$SSH_HOST "cd /var/www/html/courses-viewer-app; git pull;"

workflows:
  install:
    jobs:
      - react/install
  tests:
    jobs:  
      - react/eslint:  
          requires:  
            - react/install  
      - react/test:  
          requires:    
             - react/install  
      - react/coverage:      
           requires:      
            - react/install
            
  deploy/dev:
    machine:
      enabled: true
    jobs:
      steps:
        - run:
            name: Deploy Over SSH
            command: ssh -p 43002 $SSH_USER@$SSH_HOST "cd /var/www/html/courses-viewer-app; git pull;"
            type: approval
      requires:
        - react/eslint
        - react/test
        - react/coverage
  deploy/prod:
    jobs:
      - deploy:
          filters:
          branches:
            only:
              - main
          requires:
           - react/eslint
           - react/test
           - react/coverage
        