orbs:
    heroku: circleci/heroku@0.0.10
    node: circleci/node@4.1.0
version: 2.1

jobs:
  test:
    jobs:
      - node/test
  deploy:
    jobs:
        test
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
          requires:
             - test
workflows:
  jobs:
    - test
    - deploy

  
  
