orbs:
  react: thefrontside/react@0.2.0
version: 2.1
jobs:
  deploy:
    machine:
        enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh -p 43002 $SSH_USER@$SSH_HOST "cd /var/www/html/courses-viewer-app; git pull;"

workflows:
  install:
    jobs:
      - react/install

  tests:
    jobs:
      - react/eslint:
          requires:
            - install
      - react/test:
          requires:
            - install
      - react/coverage:
          requires:
            - install
      - deploy/dev:
          type: approval
          requires:
            - install
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - react/eslint
            - react/test
            - react/coverage
        