orbs:
    heroku: circleci/heroku@0.0.10
    node: circleci/node@4.1.0

version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    steps:
      - node/test
      - run: echo "Running tests"
  deploy:
    steps:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
          requires:
             - test
      - run: echo "Testing and deploying"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - deploy

  
  
