orbs:
  react: thefrontside/react@0.2.0
version: 2.1
jobs:
  deploy:
    machine:
        enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh -p 43002 $SSH_USER@$SSH_HOST "cd /var/www/html/courses-viewer-app; git pull;"

workflows:
  build_tests_and_deploy:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
      - deploy/dev:
          type: approval
          machine:
            enabled: true
          steps:
            - run:
                name: Deploy Over SSH
                command: ssh -p 43002 $SSH_USER@$SSH_HOST "cd /var/www/html/courses-viewer-app; git pull;"
          requires:
            - react/eslint
            - react/test
            - react/coverage
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - react/eslint
            - react/test
            - react/coverage
        